### ISSUE TITLE
Error in plugin v1.1.0

### ISSUE THREAD

**Issue by jusik0** [akamming/Domoticz_Thermostate_Plugin#4]
Hi,
there is a error in plugin v1.1.0, lines 231 - 235. The plugin works after hashing them.

**Comment by akamming** [comment]
Can you be more specific? 

What error and which specific lines did you hash? I don’t have the error you mention, and do know that if you hash the lines you mention the plug-in will not work correctly

**Comment by jusik0** [comment]
Domoticz 2022.2 log error:

2023-03-14 21:26:03.056 Status: termet: Entering work loop.
2023-03-14 21:26:03.057 Status: termet: Started.
2023-03-14 21:26:03.936 Status: termet: Initialized version 1.0.0, author 'akamming'
2023-03-14 21:26:04.367 Error: termet: Call to function 'onStart' failed, exception details:
2023-03-14 21:26:04.368 Error: termet: Traceback (most recent call last):
2023-03-14 21:26:04.368 Error: termet: File "/home/npi/domoticz/plugins/Domoticz_Thermostate_Plugin/plugin.py", line 748, in onStart
2023-03-14 21:26:04.368 Error: termet: _plugin.onStart()
2023-03-14 21:26:04.368 Error: termet: File "/home/npi/domoticz/plugins/Domoticz_Thermostate_Plugin/plugin.py", line 628, in onStart
2023-03-14 21:26:04.368 Error: termet: getSensors()
2023-03-14 21:26:04.368 Error: termet: File "/home/npi/domoticz/plugins/Domoticz_Thermostate_Plugin/plugin.py", line 350, in getSensors
2023-03-14 21:26:04.368 Error: termet: ESPCommand("GetSensors")
2023-03-14 21:26:04.368 Error: termet: File "/home/npi/domoticz/plugins/Domoticz_Thermostate_Plugin/plugin.py", line 337, in ESPCommand
2023-03-14 21:26:04.368 Error: termet: ProcessResponse(response.json())
2023-03-14 21:26:04.368 Error: termet: File "/home/npi/domoticz/plugins/Domoticz_Thermostate_Plugin/plugin.py", line 325, in ProcessResponse
2023-03-14 21:26:04.368 Error: termet: UpdateSensors(data)
2023-03-14 21:26:04.368 Error: termet: File "/home/npi/domoticz/plugins/Domoticz_Thermostate_Plugin/plugin.py", line 235, in UpdateSensors
2023-03-14 21:26:04.368 Error: termet: Devices[CURRENTHEATINGCOOLINGSTATE].Update(nValue=int(level), sValue=str(level), TypeName="Selector Switch", Options=Options)
2023-03-14 21:26:04.368 Error: termet: KeyError: 26

**Comment by akamming** [comment]
Just checked. This is indeed an issue in an old version of the plugin. But it's no longer there in the last release, i'm not going to maintain old releases. so closing...

I suggest you move to the new one as well. it is uses standard MQTT functionality and is way more accurate, making the old release obsolete...

if you want to fix anyway, create your branch and insert code which in line 235 checks if the switch is present, if if not creates it using a .Create Method instead of a .Update method..
